spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: 'false'
    suffix: .html
    check-template-location: 'true'
  devtools:
    livereload:
      enabled: 'true'
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
